site_name: Competition Backend

theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy

nav:
  - Home: 00-meta.md
  - Core: 01-core.md
  - Prerequisites: 02-prerequisite-knowledge.md
  - API: 50-source-reference/01-top.md


plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_root_full_path: true
            show_root_toc_entry: true
            show_submodules: true
            members_order: source
            separate_signature: true
            show_signature_annotations: true

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - toc:
      permalink: true